"""B06 deterministic, read-only selection of text from a B05 snapshot.

The result contains paths and decisions, never repository content. B07 owns
context inclusion and its separate file/byte/token budgets.
"""
from contextlib import ExitStack
from dataclasses import dataclass
from datetime import datetime, timezone
import os
from pathlib import Path
import re
import stat
import time
import unicodedata

from app.acquisition import AcquisitionError
from app.limits import CEILINGS
from app.snapshot import ManifestEntry, Snapshot, safe_path

POLICY_VERSION = "1"
REASONS = ("binary", "generated", "vendor", "sensitive", "unsupported_text",
           "context_budget", "submodule", "lfs")

VENDOR_DIRS = frozenset({"node_modules", "vendor", ".venv", "venv", "site-packages",
                         "third_party", "third-party", ".git", ".hg", ".svn"})
GENERATED_DIRS = frozenset({"dist", "build", "coverage", ".next", ".nuxt",
                            "__generated__", "generated", "target", "out", ".cache"})
SENSITIVE_DIRS = frozenset({".ssh", ".aws", ".kube", ".terraform", "secrets",
                            "credentials", "private_keys"})
GENERATED_NAMES = frozenset({"package-lock.json", "pnpm-lock.yaml", "yarn.lock",
                             "composer.lock", "poetry.lock", "pdm.lock", "uv.lock",
                             "cargo.lock", "gemfile.lock", "pipfile.lock", "go.sum"})
TEXT_NAMES = frozenset({"readme", "license", "dockerfile", "makefile", "gemfile",
                        "procfile", ".gitignore", ".dockerignore", ".editorconfig",
                        "jenkinsfile", "justfile"})
TEXT_SUFFIXES = frozenset({".py", ".php", ".ts", ".tsx", ".js", ".jsx", ".mjs",
                            ".cjs", ".go", ".rs", ".java", ".kt", ".rb", ".c",
                            ".cc", ".cpp", ".h", ".hpp", ".cs", ".swift", ".sh",
                            ".bash", ".sql", ".json", ".jsonc", ".yaml", ".yml",
                            ".toml", ".ini", ".cfg", ".xml", ".html", ".css",
                            ".scss", ".vue", ".svelte", ".md", ".mdx", ".rst",
                            ".txt", ".gradle", ".proto", ".tf", ".graphql"})
BINARY_SUFFIXES = frozenset({".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico",
                              ".pdf", ".zip", ".gz", ".tar", ".7z", ".woff",
                              ".woff2", ".ttf", ".otf", ".class", ".pyc", ".so",
                              ".dll", ".exe", ".wasm", ".sqlite", ".db", ".mp3",
                              ".mp4", ".mov", ".bin"})
GENERATED_HEADER = re.compile(r"(?im)^\s*(?:#|//|/\*|\*|<!--)\s*(?:@generated|code generated|"
                              r"(?:this file is )?auto[- ]generated|(?:this file is )?generated by|"
                              r"do not edit|<auto-generated>)")
PRIVATE_KEY = re.compile(r"-----BEGIN (?:[A-Z0-9 ]+ )?PRIVATE KEY-----")
TOKEN = re.compile(r"\b(?:AKIA[0-9A-Z]{16}|gh[pousr]_[A-Za-z0-9]{36,}|"
                   r"sk-[A-Za-z0-9_-]{20,}|xox[baprs]-[A-Za-z0-9-]{20,})\b")


class SelectionError(Exception):
    def __init__(self, code: str):
        super().__init__(code)
        self.code = code


@dataclass(frozen=True)
class SelectionDecision:
    path: str
    size: int
    reason: str | None


@dataclass(frozen=True)
class OmissionSummary:
    reason: str
    files: int


@dataclass(frozen=True)
class SelectionResult:
    policy_version: str
    entries: tuple[SelectionDecision, ...]
    directories: tuple[str, ...]
    omissions: tuple[OmissionSummary, ...]

    @property
    def eligible(self) -> tuple[SelectionDecision, ...]:
        return tuple(entry for entry in self.entries if entry.reason is None)

    @property
    def inventory_files(self) -> int:
        return len(self.entries)

    @property
    def eligible_files(self) -> int:
        return len(self.eligible)


def path_reason(path: str) -> str | None:
    parts = path.casefold().split("/")
    name = parts[-1]
    suffix = Path(name).suffix
    if (any(part in SENSITIVE_DIRS for part in parts[:-1]) or name == ".env"
            or name.startswith(".env.") or name in {".npmrc", ".pypirc", ".netrc",
            ".gitmodules", ".envrc", "id_rsa", "id_ed25519"}
            or name.startswith(("credentials.", "secrets."))
            or name.endswith((".pem", ".key", ".p12", ".pfx", ".keystore",
                              ".tfvars", ".tfstate", ".tfstate.backup"))
            or "service-account" in name or "service_account" in name):
        return "sensitive"
    if any(part in VENDOR_DIRS for part in parts[:-1]):
        return "vendor"
    if (any(part in GENERATED_DIRS for part in parts[:-1]) or name in GENERATED_NAMES
            or name.endswith((".min.js", ".min.css", ".map", ".pb.go", "_generated.py"))):
        return "generated"
    if suffix in BINARY_SUFFIXES:
        return "binary"
    if name not in TEXT_NAMES and suffix not in TEXT_SUFFIXES:
        return "unsupported_text"
    return None


def content_reason(data: bytes) -> str | None:
    if not data:
        return "unsupported_text"
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return "binary"
    if any(unicodedata.category(char) in {"Cc", "Cs"} and char not in "\t\n\r"
           for char in text):
        return "binary"
    if PRIVATE_KEY.search(text) or TOKEN.search(text):
        return "sensitive"
    if GENERATED_HEADER.search(text[:2048]):
        return "generated"
    return None


class FileSelector:
    def select(self, snapshot: Snapshot, limits: dict[str, int], deadline: datetime) -> SelectionResult:
        if (type(snapshot) is not Snapshot or type(limits) is not dict
                or limits.keys() != CEILINGS.keys()
                or any(type(value) is not int or not 0 < value <= CEILINGS[key]
                       for key, value in limits.items())
                or not isinstance(deadline, datetime) or deadline.tzinfo is None):
            raise SelectionError("invalid_request")
        available = (deadline - datetime.now(timezone.utc)).total_seconds()
        duration = min(limits["select_seconds"], available - limits["cleanup_seconds"])
        if duration <= 0:
            raise SelectionError("limit_exceeded")
        expires = time.monotonic() + duration
        if len(snapshot.files) > limits["file_count"]:
            raise SelectionError("limit_exceeded")
        if any(type(item) is not ManifestEntry or type(item.path) is not str
               for item in snapshot.files):
            raise SelectionError("unsafe_snapshot")

        seen: set[str] = set()
        directories: set[str] = set()
        entries: list[SelectionDecision] = []
        total = 0
        for item in sorted(snapshot.files, key=lambda entry: entry.path):
            self._check(expires)
            try:
                normalized = safe_path(item.path, limits)
            except AcquisitionError as error:
                raise SelectionError(error.code) from None
            if normalized != item.path or item.path in seen or type(item.size) is not int or item.size < 0:
                raise SelectionError("unsafe_snapshot")
            seen.add(item.path)
            if item.size > limits["file_bytes"]:
                raise SelectionError("limit_exceeded")
            total += item.size
            if total > limits["extracted_bytes"]:
                raise SelectionError("limit_exceeded")
            if item.omission not in (None, "lfs", "submodule"):
                raise SelectionError("unsafe_snapshot")
            parts = item.path.split("/")
            directories.update("/".join(parts[:index]) for index in range(1, len(parts)))
            reason = item.omission or path_reason(item.path)
            if reason is None:
                reason = content_reason(self._read(snapshot.root, item, limits, expires))
            entries.append(SelectionDecision(item.path, item.size, reason))
        counts = {reason: 0 for reason in REASONS}
        for entry in entries:
            if entry.reason is not None:
                counts[entry.reason] += 1
        return SelectionResult(POLICY_VERSION, tuple(entries), tuple(sorted(directories)),
                               tuple(OmissionSummary(reason, counts[reason]) for reason in REASONS
                                     if counts[reason]))

    @staticmethod
    def _check(expires: float) -> None:
        if time.monotonic() >= expires:
            raise SelectionError("limit_exceeded")

    @classmethod
    def _read(cls, root: Path, item: ManifestEntry, limits: dict[str, int], expires: float) -> bytes:
        directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC
        file_flags = os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC | os.O_NONBLOCK
        try:
            with ExitStack() as stack:
                fd = os.open(root, directory_flags)
                stack.callback(os.close, fd)
                parts = item.path.split("/")
                for segment in parts[:-1]:
                    cls._check(expires)
                    fd = os.open(segment, directory_flags, dir_fd=fd)
                    stack.callback(os.close, fd)
                file_fd = os.open(parts[-1], file_flags, dir_fd=fd)
                stack.callback(os.close, file_fd)
                info = os.fstat(file_fd)
                if not stat.S_ISREG(info.st_mode) or info.st_size != item.size:
                    raise SelectionError("unsafe_snapshot")
                chunks = []
                count = 0
                while True:
                    cls._check(expires)
                    chunk = os.read(file_fd, 16384)
                    if not chunk:
                        break
                    count += len(chunk)
                    if count > item.size or count > limits["file_bytes"]:
                        raise SelectionError("unsafe_snapshot")
                    chunks.append(chunk)
                if count != item.size:
                    raise SelectionError("unsafe_snapshot")
                return b"".join(chunks)
        except OSError:
            raise SelectionError("unsafe_snapshot") from None
