<?php

return [
    'internal_url' => env('AI_INTERNAL_URL', 'http://ai:8000'),
    'internal_secret' => env('AI_INTERNAL_SECRET', ''),
    'limits' => [
        'public_body_bytes' => 4096,
        'archive_bytes' => 20971520,
        'download_bytes' => 52428800,
        'extracted_bytes' => 104857600,
        'file_count' => 2000,
        'path_depth' => 12,
        'path_characters' => 512,
        'file_bytes' => 1048576,
        'archive_entries' => 4000,
        'context_files' => 100,
        'context_bytes' => 262144,
        'context_spans' => 500,
        'context_tokens' => 12000,
        'input_tokens' => 16000,
        'output_tokens' => 6000,
        'attempt_tokens' => 44000,
        'max_findings' => 20,
        'evidence_per_finding' => 5,
        'internal_body_bytes' => 32768,
        'internal_response_bytes' => 1048576,
        'active_analyses' => 1,
        'queued_analyses' => 10,
        'outbound_concurrency' => 1,
        'submissions_per_minute' => 6,
        'connect_seconds' => 5,
        'github_request_seconds' => 30,
        'provider_request_seconds' => 60,
        'github_requests' => 8,
        'redirects' => 2,
        'acquire_seconds' => 75,
        'select_seconds' => 10,
        'context_seconds' => 10,
        'generate_seconds' => 125,
        'validate_seconds' => 10,
        'cleanup_seconds' => 10,
        'overall_seconds' => 240,
        'worker_http_seconds' => 255,
        'job_seconds' => 270,
        'attempt_lease_seconds' => 285,
        'redis_reservation_seconds' => 300,
        'reconcile_seconds' => 30,
        'operation_tries' => 2,
        'operation_backoff_seconds' => 1,
        'automatic_attempts' => 2,
        'total_attempts' => 3,
        'attempt_backoff_seconds' => 5,
    ],
    'ai_limit_keys' => [
        'archive_bytes',
        'download_bytes',
        'extracted_bytes',
        'file_count',
        'path_depth',
        'path_characters',
        'file_bytes',
        'archive_entries',
        'context_files',
        'context_bytes',
        'context_spans',
        'context_tokens',
        'input_tokens',
        'output_tokens',
        'attempt_tokens',
        'max_findings',
        'evidence_per_finding',
        'internal_response_bytes',
        'outbound_concurrency',
        'connect_seconds',
        'github_request_seconds',
        'provider_request_seconds',
        'github_requests',
        'redirects',
        'acquire_seconds',
        'select_seconds',
        'context_seconds',
        'generate_seconds',
        'validate_seconds',
        'cleanup_seconds',
        'overall_seconds',
        'operation_tries',
        'operation_backoff_seconds',
    ],
];
